name: anitomy_dart
description: A dart port of anitomy, a C++ library for parsing anime video filenames.
version: 1.0.0
repository: https://github.com/senzmaki/anitomy_dart

environment:
  sdk: ^3.9.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
